import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full bg-white border-b border-gray-200 py-4 px-8 flex gap-8 items-center shadow-sm mb-8">
          <a href="/" className="font-bold text-lg hover:text-blue-600 transition-colors">Home</a>
          <a href="/about" className="hover:text-blue-600 transition-colors">About Us</a>
          <a href="/services" className="hover:text-blue-600 transition-colors">Services</a>
          <a href="/portfolio" className="hover:text-blue-600 transition-colors">Portfolio</a>
          <a href="/contact" className="hover:text-blue-600 transition-colors">Contact</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
